// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgctizhfwngianypbztg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnY3Rpemhmd25naWFueXBienRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NTY4NzcsImV4cCI6MjA1ODUzMjg3N30.ZwjlRx3_VFyLHpeQBvXBdPJrKN2ISnk8y_JbY8OFizY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);